on: [pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch:
          - {distro: dunfell, version: 3.1.17}
          # - {distro: gatesgarth, version: 3.2.4} #EOL
          # - {distro: hardknott, version: 3.3.6}  #EOL
          # - {distro: honister, version: 3.4.4}   #EOL
          - {distro: kirkstone, version: 4.0.1}
    env:
      YOCTO_VERSION: ${{ matrix.branch.version }}
      YOCTO_BRANCH: ${{ matrix.branch.distro }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'meta-rust'
      - name: Fetch poky
        run: |
          mv poky/build/sstate-cache . || true
          rm -rf poky meta-openembedded
          git clone -b $YOCTO_BRANCH --single-branch git://git.yoctoproject.org/poky
          git clone -b $YOCTO_BRANCH --single-branch git://git.openembedded.org/meta-openembedded
      - name: Configure build
        run: |
          cd poky
          . oe-init-build-env
          mv ../../sstate-cache . || true
          bitbake-layers add-layer ../../meta-openembedded/meta-oe
          bitbake-layers add-layer ../../meta-rust
          echo 'PARALLEL_MAKE:pn-rust-llvm-native = "-j2"' >> conf/local.conf
          echo 'TOOLCHAIN_HOST_TASK:append = " packagegroup-rust-cross-canadian-${MACHINE}"' >> conf/local.conf
          echo 'PREFERRED_PROVIDER_virtual/kernel = "linux-dummy"' >> conf/local.conf
          echo 'INHERIT:remove = "uninative"' >> conf/local.conf
      - name: Run bitbake
        run: |
          cd poky
          . oe-init-build-env
          bitbake rust-hello-world
